collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

staticmanURL: "https://staticmanthaiviwedding.vercel.app/v3/entry/github/demo_jekyll/main/comments"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag